"""03_order/w01_market_order - 시장가 주문"""


def get_workflow():
    return {
        "id": "order-01-market",
        "version": "1.0.0",
        "name": "시장가 주문 예제",
        "description": "RSI 조건 만족 시 시장가 매수",
        "nodes": [
            {
                "id": "start",
                "type": "StartNode",
                "category": "infra",
                "position": {"x": 0, "y": 200},
            },
            {
                "id": "broker",
                "type": "BrokerNode",
                "category": "infra",
                "provider": "ls-sec.co.kr",
                "product": "overseas_stock",
                "position": {"x": 200, "y": 200},
            },
            {
                "id": "schedule",
                "type": "ScheduleNode",
                "category": "trigger",
                "cron": "*/30 * * * * *",
                "timezone": "America/New_York",
                "position": {"x": 400, "y": 200},
            },
            {
                "id": "watchlist",
                "type": "WatchlistNode",
                "category": "symbol",
                "symbols": [{"exchange": "NASDAQ", "symbol": "AAPL"}],
                "position": {"x": 600, "y": 100},
            },
            {
                "id": "account",
                "type": "RealAccountNode",
                "category": "realtime",
                "fields": ["balance"],
                "position": {"x": 600, "y": 300},
            },
            {
                "id": "marketData",
                "type": "RealMarketDataNode",
                "category": "realtime",
                "fields": ["price", "volume"],
                "position": {"x": 800, "y": 100},
            },
            {
                "id": "rsiCond",
                "type": "ConditionNode",
                "category": "condition",
                "plugin": "RSI",
                "fields": {"period": 14, "threshold": 30, "direction": "below"},
                "position": {"x": 1000, "y": 200},
            },
            {
                "id": "order",
                "type": "NewOrderNode",
                "category": "order",
                "plugin": "MarketOrder",
                "fields": {"side": "buy", "quantity": 1},
                "position": {"x": 1200, "y": 200},
            },
            {
                "id": "display",
                "type": "DisplayNode",
                "category": "display",
                "format": "table",
                "fields": ["symbol", "side", "price", "quantity", "status"],
                "position": {"x": 1400, "y": 200},
            },
        ],
        "edges": [
            {"from": "start", "to": "broker"},
            {"from": "broker", "to": "schedule"},
            {"from": "schedule", "to": "watchlist"},
            {"from": "watchlist", "to": "marketData"},
            {"from": "broker", "to": "account"},
            {"from": "marketData", "to": "rsiCond"},
            {"from": "rsiCond", "to": "order"},
            {"from": "account", "to": "order"},
            {"from": "order", "to": "display"},
        ],
    }
